jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm run build
      - run: pnpm run test:create
      - if: always()
        name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage-create/lcov.info
          flags: create

name: Test Creation Script

on:
  pull_request: ~

  push:
    branches:
      - main
